<a href="https://colab.research.google.com/github/rishitdass/assignments/blob/main/assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
ar=np.array([1,2,3,4,5,6])

1st question

In [ ]:
ar_r=ar[::-1]
ar_r

array([6, 5, 4, 3, 2, 1])

2nd question

In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])


In [ ]:
arr1==arr2

array([[ True,  True],
       [ True,  True]])

In [ ]:
np.array_equal(arr1,arr2)

True

3rd question


In [ ]:
x=np.array([1,2,3,4,5,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3,3])

In [ ]:
def most_freq(arr):
  array,count=np.unique(arr,return_counts=True)
  most_freq_element=array[np.argmax(count)]
  indeces=[]
  for i in range(len(arr)):
    if arr[i]==most_freq_element:
     indeces.append(i)
  print(f"most frequent element: {most_freq_element}`, and its indeces are{indeces}")

In [ ]:
most_freq(x)

most frequent element: 1`, and its indeces are[0, 6, 7, 8]


In [ ]:
most_freq(y)

most frequent element: 3`, and its indeces are[4, 8, 9, 10]


Question 4

In [ ]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')

In [ ]:
sum=np.sum(gfg)
sum_row=np.sum(gfg,axis=1)
sum_col=np.sum(gfg,axis=0)
sum,sum_row,sum_col

(45,
 matrix([[14],
         [16],
         [15]]),
 matrix([[20,  9, 16]]))